### ISSUE TITLE
1.1x-5.8.2 won't accept coal for Actually Additions

### ISSUE THREAD

**Issue by kreezxil** [McJty/RFTools#1001]
There are no errors in server or client console when we try to do it, it just won't let us put it in there. The AA coal works fine in a vanilla furnace.

**Comment by McJty** [comment]
That's actually on purpose atm. The coal generator is currently hardcoded for vanilla coal and coal blocks. Not sure if I want to extend that or not

**Comment by kreezxil** [comment]
It makes the generator appear broken when used with other mods that provide coal type blocks. 

-----Original Message-----

**Comment by McJty** [comment]
Well that's not a valid argument. The documentation only mentions coal and coal block. Nothing else.

**Comment by kreezxil** [comment]
Do you expect players to look at your documentation when they craft your generator after they discover that? Because they're not, instead they're complaining to me and the server admins that run my packs that your coal generator is broke.

Whether or not you think that is valid doesn't matter to me.

I did my job and reported it.



-----Original Message-----

**Comment by McJty** [comment]
Actually I *do* expect players to look at my documentation BEFORE they craft my generator. Not after. That's what documentation is for isn't it? To give people essential information. If they don't read it then that's NOT my fault. The reason my coal generator only accepts coal and coal blocks is a balance thing. Be aware that fully infused my coal generator is most likely the most efficient coal generator in modded Minecraft (at least it was some time before, haven't checked if things have changed since then). So some balancing to offset that is needed IMHO
