### ISSUE TITLE
[1.10.2] Energy Module no longer works for Mekanism Induction Matrix

### ISSUE THREAD

**Issue by JonoColwell** [McJty/RFTools#1013]
It is no longer possible to set an Energy module to monitor the total power in a Mekanism Induction Matrix, you can set the module to monitor an induction port however that gives an incorrect reading, attempting to shift click on anything other than the induction port causes it to clear the module.

RFtools ver: 1.1x-5.81

Mekanism Ver: 9.2.1

http://puu.sh/tBS8Q/ec1b0b5798.jpg

http://puu.sh/tBS9V/9e6a4a9094.jpg

http://puu.sh/tBSat/f1a37dfc53.jpg

http://puu.sh/tBSce/83559965ad.jpg

**Comment by JonoColwell** [comment]
It also does not monitor Draconic Evolution energy balls correctly, same issue.

**Comment by bigcarl35** [comment]
There's also now a problem with monitoring an EnderIO capacitor bank.  It shows you the energy for the block you clicked and not the whole multiblock capacitor bank.  This use to work, so I was surprise to find this change.

**Comment by McJty** [comment]
Will probably be fixed in upcoming release of McJtyLib (for Mekanism, Draconic Evolution, and EnderIO). Untested so feedback is welcome.

I would appreciate it if some of you could test this with this test build on jenkins:

http://jenkins.k-4u.nl/job/McJtyLib%201.11/lastSuccessfulBuild/artifact/build/libs/mcjtylib-1.1x-2.3.6-SNAPSHOT.jar

Just replace McJtyLib 2.3.5 with this and see if you can now read out bigger values with the screen energy module or the rf monitor block

**Comment by jeridan** [comment]
Downloaded and testing but I currently do not see any difference in behavior.  The power monitor doesn't see the max power available in the draconic evolution energy sphere and it will not adjust a redstone signal based on it.

**Comment by McJty** [comment]
Um, that screenshot is not my power monitor. That's from EnderIO. I have nothing to do with that

**Comment by jeridan** [comment]
Your right, grabbed the wrong screenshots because I was testing multiple setups and derped hard.  Appears as though the mcjtylib-1.1x-2.3.6-SNAPSHOT.jar is working as expected.  I can now control my power plants with the RF Monitor.
