### ISSUE TITLE
Sleeping in midnight dimentions.

### ISSUE THREAD

**Issue by DeForce** [McJty/RFTools#117]
Good Day,

We have created dimension with time midnight and we are having issue with setting spawnpoint on bed in it.
Is it possible to set a spawn point, but not sleeping in bed, because I'm unable to sleep in bed in the midnight dimension? Mystcraft permits sleeping in bed when having midnight age.

Best Regards,
DeForce.

**Comment by McJty** [comment]
RFTools has a config for this:

    # Behaviour when sleeping in an RFTools dimension: 0 = do nothing, 1 = explode, 2 = set spawn
    I:bedBehaviour=0

If you set this to 2 then you can sleep in a bed. The sleeping will not work but it will set your spawn point.

However you also need to set:

    # If this flag is true the player will respawn in the rftools dimension when he dies (unless power runs out)
    B:respawnRfToolsDimension=true

To make sure you can respawn in rftools dimensions.

**Comment by DeForce** [comment]
Thanks, missed it in the configs.
I have set special spawn dimlet for that, does that count as true for this dimension, as when they die they respawn in that dimenstion.

**Comment by McJty** [comment]
yes, the spawn dimlet would work too

**Comment by astradamus** [comment]
Why exactly does night-skipping with beds not work in custom dimensions? Is this a limitation of how the game does custom dimensions? Since you've clearly been able to override standard bed behavior when the option is set for the spawn switch--perhaps custom code could force the time to advance to dawn in much the same way, regardless of whether you properly 'sleep' in the bed?
