### ISSUE TITLE
When crafting in the storage scanner, the items in the scanned inventories disappear rather than craft.

### ISSUE THREAD

**Issue by T3ctonic** [McJty/RFTools#1294]
As title says, unfortunately this is all I can provide but it seems easily repeatable as I have done it multiple times. Resonant Rise version: 4.3.0.0-b. RFTools version: "RFTOOLS-1.1X-6.10"
Video: https://www.youtube.com/watch?v=GR_b6TK8A-s

**Comment by McJty** [comment]
Hmm this has been reported before but I have never been able to reproduce it. Where was that gold stored? What kind of block is that?

**Comment by McJty** [comment]
https://github.com/McJty/RFTools/issues/1231

**Comment by McJty** [comment]
What version of Minecraft is that btw? Also I suppose the medium storage crate is from Actually Additions? What version?

**Comment by T3ctonic** [comment]
It was inside a actually additions crate however, it would remove all items from chests also. Minecraft version 1.10.2 Actually Additions version: "ACTUALLYADDITIONS-1.10.2-R105"

**Comment by T3ctonic** [comment]
I will see if I can reproduce it in a creative world

**Comment by T3ctonic** [comment]
I am unable to replicate with just the barrels and chests in a fresh creative and survival world. I can only think that I had an active void miner filling a crate on the scanner at the same time, so that may cause problems as I said I do not know.

**Comment by McJty** [comment]
I'm seeing if I can simply rewrite the code to be more robust

**Comment by McJty** [comment]
I think I have a fix. Even though I cannot reproduce the problem. I will publish a new version soon and I hope you will be able to test it to see if it ok now

**Comment by McJty** [comment]
I hopefully fixed this in 6.12. Let me know if the fix helps

**Comment by T3ctonic** [comment]
After updating rftools, the problem seems to be fixed, thanks :D

**Comment by McJty** [comment]
Ok good to know!

**Comment by Senjar** [comment]
I think this bug is back.

Version:
rftools-1.12-7.61
rftoolsctrl-1.12-1.9.3
rftoolsdim-1.12-5.64

Modpack: Enigmatica 2 Expert v1.58

Video:
https://www.youtube.com/watch?v=33jpI62BGnI

The weird thing is that it only deletes 2 torches instead of 4 that the recipe needs.
The red background when you don't have the required items never appears in this scanner for all recipes. I thought it was removed until I checked a scanner with only 1 chest in a new save.
Also, note that I don't have any oak wood. Only birch.
When I swap to birch wood in the recipe it works.

**Comment by mmarquezs** [comment]
@Senjar In my case I think it was the forestry workbench that were causing issues. After removing them it would stop dissapearing the items and it was showing the red background. I also removed the bibliocraft bookshelfs but I don't think it was that.
