### ISSUE TITLE
RFTools Takes Longer to Close Out of a World With The More Mods You Have

### ISSUE THREAD

**Issue by Darkosto** [McJty/RFTools#1390]
Hello! 

When running a pack with a significant number of mods: Save and Quit back to the main menu RFtools does not close out of the previous world quickly, which causes the modpack to freeze and crash when you open a new world. The only way I can reproduce is with a lot of mods in the pack. Having a small group of mods will allow RFTools to close out quickly.

"[15:27:49] [Server thread/INFO] [mcjty.lib.varia.Logging]: RFTools: server is stopping. Shutting down gracefully"

This has been a problem from MC 1.11 through 1.12, through a range of forge versions, and RFTools versions. Is there any way you could look into closing out the previous worlds quicker when a pack is running with a large number of mods?

Thanks for your time!
Darkosto

**Comment by McJty** [comment]
What? RFTools doesn't do anything. I should have removed that 'Shutting down gracefully' message a long time ago because it points fingers at RFTools while that simply means that RFTools is closing :-)

If there are more mods then closing down Minecraft will take more time but I doubt RFTools has anything to do with that though. I would have no clue how in any case

**Comment by Darkosto** [comment]
Ahh, well I noticed the game freezes when particular message does not have time to show up. But, it seems like that's just a coincidence. Looks like I'll need to dig further into it and figure out what is causing it. 

Thanks!
