### ISSUE TITLE
[1.12.2] [rftools-1.12-6.13] builder ignores filter card

### ISSUE THREAD

**Issue by winsrp** [McJty/RFTools#1397]
So very simple, I setup my builder, make a filter card, put in cobble and dirt as blacklisted blocks, put the filter card in the builder, i also put a normal quarry card (non clearing non fortune non anything), hook up some power, put a chest on top, a lever in front and run.

Chest above starts filling with cobble and dirt, among the rest of the stuff it finds.

**Comment by McJty** [comment]
Ok. You have to init the filter with the material that it is BEFORE it is mined. Since the world does not contain cobble usually (but normal stone) you have to put stone in the filter. Additionally the dirt is probably coming from the grass blocks that are being harvested. So you have to put grass blocks in the filter as well

**Comment by winsrp** [comment]
hmm.... tricky, thanks

**Comment by McJty** [comment]
Note that you can put stone and grass in a filter item by sneak right clicking that item on stone and grass. You don't need to be able to actually harvest those

**Comment by winsrp** [comment]
oh cool, thanks for the info! great mod as always!
