### ISSUE TITLE
Pump doesn't pick up desired liquid

### ISSUE THREAD

**Issue by Shykel** [McJty/RFTools#1411]
I'm using itanks, thermal expansion and the latest rftools and I was trying to get some lava on the overworld but the pump would keep trying to pick up water even with a small amount of lava already in the tank. It would never actually pick up the water block but just freezes

![](https://i.imgur.com/gFe96m6.jpg)

![](https://i.imgur.com/ipPnEmr.png)

![](https://i.imgur.com/62ujQLK.jpg)

![](https://i.imgur.com/nC4ICTO.jpg)

**Comment by McJty** [comment]
Ok I know what's up. It is because it has no place for the water so it waits. Easiest solution is to place another tank at the bottom for water. Another solution is to have several output tanks which are all connected to the top tank. Every output tank will fill with the appropriate liquid so the output tank above the builder remains empty most of the time
