### ISSUE TITLE
Suggestion: control builder block quarrys with the scanner.

### ISSUE THREAD

**Issue by Morelyn** [McJty/RFTools#1415]
currently (rftools 7.11 in minecraft 1.10.2) it appears that if you put a scanned quarry card into a builder, it mines out the scanned shape in relation to the builder block itself...

It would be very nice if builders could use both the location and filtering of the scanner to control where its mining (you could also pair it with the projector for a visual display of blocks still to mine

**Comment by McJty** [comment]
That's not going to change. The idea is exaclty that you can use the Builder on a scancard elsewhere. Letting it work on the same location is pretty useless IMHO. Note that you can change the offsets in the scan card so that it again matches the original location but I will not change how it works as that is not how the builder works and I can't make a special case in the usage of the offset parameters for only one type of card.
