### ISSUE TITLE
Can't change builder mode

### ISSUE THREAD

**Issue by MrRiegel** [McJty/RFTools#1445]
rftools 1.12 7.13
mcjtylib 1.12 2.4.5
forge 14.23.0.2527

https://gist.github.com/MrRiegel/e42c61d6349068b457f93d04f6543574

**Comment by McJty** [comment]
And what exactly are you doing in game to cause that problem? Details please

**Comment by MrRiegel** [comment]
I put a space chamber card into the builder and try to change mode from `copy` to `move`. when i click the button it changes the mode only on client and the crash appears in the log.

**Comment by McJty** [comment]
ok. I will check it out. Is the shape card linked to a controller?

**Comment by MrRiegel** [comment]
yes. preview works too

**Comment by SparkVGX** [comment]
# Description
Builder will not allow changing mode for space chamber card. Clicking the mode button visually scrolls through options, but machine does not actually change mode.

# Expected Behavior
When clicking the mode button, with a correctly setup chamber and chamber card, machine should cycle through options. On leaving GUI and going back in, machine should be on the last mode option selected and functionally use that mode.

# Steps to Reproduce

1. Set up space chamber as expected and set the space chamber card id to it. 
2. Place card in builder
3. Cycle through mode options
4. Leave GUI
5. Go back into GUI, setting has gone back to copy mode.

Image attached shows world space GUI not being synced with GUI of machine.
![javaw_2017-11-10_12-24-59](https://user-images.githubusercontent.com/3460315/32634786-409c6e16-c612-11e7-824c-9e42925ec19e.png)


# Technical Details

Minecraft 1.12.2
Forge 14.23.0.2529
RFTools 1.12-7.13

**Comment by gabeux** [comment]
Unfortunately having the same issue on the Space Astronomy 2 modpack.
Minecraft 1.10.2, rftools-1.1x-7.13, Forge 12.18.3.2511

Tried changing the Tile Entity options on the builder RFTools configs (as I thought it had something to do with that), but no effect.

**Comment by ouroborus** [comment]
We're having this same issue in ATM3. Click the button cycles, but the display over the machine doesn't update and exiting then re-entering the GUI shows it back at copy.

**Comment by McJty** [comment]
I found the problem. Will be fixed next release
