### ISSUE TITLE
Crafter crash after updating several mods.

### ISSUE THREAD

**Issue by valveo** [McJty/RFTools#159]
My server somehow crash after updating several mods.
Tested with forge 1291 and also newer, downgraded mod to 2.75 and 2.76, didnt help.

Crashlog: http://pastebin.com/Zh2GrVXr

**Comment by McJty** [comment]
Do you know what kind of recipes are in it?

**Comment by McJty** [comment]
The problem is most likely that you were using recipes that have changed (due to a mod updating) or the resulting item no longer is valid. I will make the crafter more robust so that it no longer crashes in this situation. In the mean time I recommend reverting your updates and clearing the crafters for possible recipes that may be changed in the mods you were updating.
