### ISSUE TITLE
Powercells don't accept energy from Career Bees' energy bees

### ISSUE THREAD

**Issue by JulianTrei** [McJty/RFTools#1642]
Issue description: 
Not really an issue but not sure if you knew: 
The Powercell is not accepting energy from industrial apiary (energy bees inside) in FTB Revelation.
Obvious fix below
![mc_1](https://user-images.githubusercontent.com/30473934/36336437-1446f106-1388-11e8-8ca9-9ace473deace.png)
Thanks for the awesome mod!

**Comment by McJty** [comment]
Hmm the powercell just follows normal RF API. So not sure what could be wrong on our side

**Comment by josephcsible** [comment]
The problem is that energy bees ask for the energy capability of the null/internal side of the block, and try to put their energy there: https://github.com/rwtema/Careerbees/blob/97d2556d95d33b4524a86e6b80bac086135dd285/src/main/java/com/rwtema/careerbees/effects/EffectPower.java#L49-L51

However, our powercells are set up to not be able to accept energy on the null/internal side, ever: https://github.com/McJty/RFTools/blob/1.12/src/main/java/mcjty/rftools/blocks/powercell/PowerCellTileEntity.java#L761-L766

**Comment by josephcsible** [comment]
I'm not going to leave this open any longer, since there's nothing further we can do about this. If you want this to get fixed, ask @rwtema to merge rwtema/Careerbees#14.

**Comment by mjevans** [comment]
I took my own stab at fixing this while fixing a server-crash causing issue with Assassin bees.  Hopefully it's accepted.

https://github.com/rwtema/Careerbees/pull/39
