### ISSUE TITLE
Clientcrash on Opening SSP World

### ISSUE THREAD

**Issue by Esriel123** [McJty/RFTools#17]
So i got the following Crash when trying to Start a Singleplayer world in my instance. I am Playing this instance on a server and it works just fine. 

Forge Version: 10.13.2.1277

RF Tools Version: 2.10

Crashlog Link: http://pastebin.com/NSVZfBxj

**Comment by Esriel123** [comment]
Also on the Server i am Finding Dimlets with no texture and that are called unnamed. The Digit Dimmlet is one of them as you can see in the following pictures:

http://puu.sh/el9mR/c0d5ca22d5.jpg while Crafting 

http://puu.sh/el9rV/7e2b061b3e.jpg when pulled from the Crafting table

**Comment by McJty** [comment]
The second issue is a problem with your dimlets.cfg being outdated on client vs server. The dimlets.cfg must be exactly the same on the client and the server. You should have gotten some warning messages on this problem in the client log.

The first issue is weird. Did you perhaps update some mods or configs so that dimension 8 is now taken by something else?

**Comment by Esriel123** [comment]
The First issue was acctually due to me updating to 2.10 but forgetting to let the config recreate. Thx for the help with the config missmatch from server to client.

**Comment by McJty** [comment]
Be careful to update dimlets.cfg in the future. It should actually *not* be recreated on existing worlds from this version on because it contains important mapping information. main.cfg is safe to remove.
