### ISSUE TITLE
Storage Scanner Fatal Error Console Spam

### ISSUE THREAD

**Issue by LunixNovalis** [McJty/RFTools#2071]
Issue description: Server Console spam when crafting with Storage Scanner. Doesn't affect gameplay, but "Fatal Error" console spam was concerning.

Steps to reproduce: Connect inventories to Storage Scanner and craft something inside the Scanner.

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.12.2-3.5.4
* RFTools: 1.12.2-7.73

Possibly incompatible mods and versions: MC Eternal Modpack (Version: 1.3.5.3) / Optifine 1.12.2_HD_U_F5

Relevant logs, if any:  [Pastebin](https://pastebin.com/NjLkjTcL)

**Comment by McJty** [comment]
This is caused by a bug in one of the blocks that the storage scanner is trying to access. Try to remove some of the blocks from the scanner view until you find the one that causes it. The issue is that this code fails:

        if (tileEntity != null && tileEntity.hasCapability(CapabilityItemHandler.ITEM_HANDLER_CAPABILITY, null)) {
            IItemHandler capability = tileEntity.getCapability(CapabilityItemHandler.ITEM_HANDLER_CAPABILITY, null);
            for (int i = 0 ; i < capability.getSlots() ; i++) {


That basically means that hasCapability() returns true while getCapability() returns null. That's a bug in that mod. If you can find which mod causes it you can tell this to them

**Comment by LunixNovalis** [comment]
That was it. I forgot to delete a chest from the scanner. Thanks for the reply.
