### ISSUE TITLE
Duplicating items when middle click on storage module intalled in modular storage

### ISSUE THREAD

**Issue by diegofpais** [McJty/RFTools#2090]
Issue description: Duplicating items, moving to player inventory overwriting what's in it (including storage module) when middle click on storage module intalled in modular storage
[2020-08-30-04-52-441.zip](https://github.com/McJtyMods/RFTools/files/5146475/2020-08-30-04-52-441.zip)

Steps to reproduce: Player's inventory full. Middle click on storage module intalled in modular storage (see attached video)

Versions:
* Minecraft: 1.15.2
* Forge: 31.2.36
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 4.1.4
* RFTools: 1.1.3

Possibly incompatible mods and versions: 

Relevant logs, if any:

**Comment by McJty** [comment]
Hmm, by default middle click on an item in a gui has no functionality. Do you have a mod that adds some functionality to that button? I guess the problem is with that mod then. I cannot reproduce this.

I just noticed your video. You are in creative. Of course middle click duplicates the items. That's what middle click does in creative
