### ISSUE TITLE
Crash when setting shield material to EnderIO Quite Clear Glass

### ISSUE THREAD

**Issue by LachlanArthur** [McJty/RFTools#21]
Crash when these things happen:
- Set shield material to Quite Clear Glass from EnderIO
- Put block of Quite Clear Glass touching shield block
- Set shield type to Solid (or SolDmg)
- Enable the shield

Screenshot of setup:
![image](https://cloud.githubusercontent.com/assets/1870204/5958530/23ab98ee-a811-11e4-90ca-8f5dca17e7d5.png)

![image](https://cloud.githubusercontent.com/assets/1870204/5958493/c085f96c-a810-11e4-9388-da3aa882ea68.png)

Pastebin of crash:
http://pastebin.com/3G2Nd7qL

**Comment by McJty** [comment]
Thanks for the report. I will investigate this. BTW, with what version of RFTools did you get this?

**Comment by LachlanArthur** [comment]
The version is 2.20

**Comment by McJty** [comment]
I cannot reproduce the crash although the block does render wrong though. I also know why but currently have no real idea on how to fix this properly.

**Comment by excid** [comment]
I can extend this, and I'm using version 2.31a(Feed the Beast Infinity 1.0.0)

Solid textures with the shield templates and connected textures seams to be working.
I tried it with the Big Reactors, Reactor Glass(Turbine Glass too).

But: When you configure it like this (image below), it will continues crash. If only set to solid, without any other configuration, it works fine.

![2015-02-06_10 12 46](https://cloud.githubusercontent.com/assets/5160504/6076861/0979d85e-ade9-11e4-932b-b82c43de2583.png)

When using blocks like from Chisel or Vanilla, their is no Crash. Even AE2 ME Drives are working x)
Me didnt tested sooo much blocks, since restarting the game takes houres for me. But i guess it's hopefully a good starting for you, to reproduce.

Pastebin of Crashreport: http://pastebin.com/3we5Qn6p

**Comment by McJty** [comment]
Still working on this but I think I partially fixed it. At least it shouldn't crash anymore but the blocks still don't show correctly.

**Comment by McJty** [comment]
Ok, I managed to fix this. Will be ok in next release.
