### ISSUE TITLE
Modular Storage

### ISSUE THREAD

**Issue by Dylanh765** [McJty/RFTools#2102]
Issue description: Somehow managed to put all items from modular storage into my inventory, overwriting what was in my inventory and it removed the storage card from the modular storage block. Lost all stored items.

Steps to reproduce: Middle clicked in the wrong spot?

Versions:
* Minecraft: 
* Forge: 
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib:
* RFTools:

Possibly incompatible mods and versions: 

Relevant logs, if any:

**Comment by McJty** [comment]
Can you please fill in the version numbers? You left everything empty

**Comment by korncola** [comment]
I had the same in 1.16.4. just press the A-Z Button next to inventory when in modular storage screen.
it will overwrite held inventory with all that fits, rest is gone (and not dropped). And mostly likely it wil be the module storage card itself. 

Also duping possible: Step to reproduce:
Put in 1 stack
Press A-Z
get module with 1 stack and 1 stack itself
Profit

**Comment by McJty** [comment]
Inventory Tweaks present?

**Comment by Bogual** [comment]
I had the same isue in 1.16.4. Yes, Inventory Tweaks is present. It seems, that it has to do with the sorting function.

**Comment by McJty** [comment]
There is a very bad interaction bug going on between inventory tweaks and rftools storage that I haven't been able to pinpoint yet. Also not sure what side the problem is on

**Comment by Skar78** [comment]
Modpack: ATM6 v1.3.3 - without any change of pack or config besides adding a texture pack (bdcraft).

Same issue - middle click in my inventory while modular storage GUI open = everything gone.

I had also a Backpack from the mod useful backpacks in the hot bar, - only item magically survived.
Also I noticed that my armor was put into the crafting grid and some random items into the backpack.

Unfortunately the Tier 3 module card was simply gone.

**Comment by McJty** [comment]
I know this problem. It is caused by inventory tweaks. No solution (on either rftools or inv tweaks side) is presently available

**Comment by Skar78** [comment]
Well, glad to hear that it is known. Keep up the good work!

**Comment by McJty** [comment]
I implemented a workaround for this problem for the next update of this mod

**Comment by desagas** [comment]
@McJty, some more info for you, and a suggestion:

1st, the crash does not happen on my mac, version in ATM6 1.3.3. I was in creative when I tried it, and all middle click did was, A, nothing when not middle clicking on something, and B, removing all items including the module and putting them into my inventory when middle clicking on an actual item in the window. _EDIT: Apparent, that was what has been happening a lot. Ugh._ **BUT: it does not change the items stored in it under the UUID!! I can only assume this is because the click removes everything seemingly at once, disallowing the MS/Tablet to update the inventory of the module.**

2nd, can you please make the UUID selectable and copyable from the "/rftoolsstorage list" function ... OR ... make it so that a list of UUIDs pop up when tabbing after "/rftoolsstorage restore" so that we can select a UUID from the list?

Here is what I shared with the ATM6 team: 
> Oh, yeas. I found a fix for the RFTools middle click problem. IF someone middle clicks and crashes, they can "/rftoolsstorage list" and then copy the uuid down, manually, and then "/rftoolsstorage restore UUIDHERE." This will prevent people from having to load from a backup, but does require cheats to be enabled, AND, they must have the EXACT same 1/2/3/4 module in hand that was lost.

**Comment by McJty** [comment]
I have no clue how to do that but note that you don't have to type in the entire UUID. If you type in enough of the first letters of the UUID so that there can be no doubt then that will work
