### ISSUE TITLE
[Request][Mod Interaction] Method/Interface/API Hook to blacklist certain blocks or (especially) fluids from the dimensions

### ISSUE THREAD

**Issue by ReikaKalseki** [McJty/RFTools#234]
I think you can see why I need this. :P

**Comment by McJty** [comment]
Yes, this is something that is already on my todo. In recent versions of RFTools I did increase the rarity/cost of several of RotaryCraft/ReactorCraft's fluids already though (which is IMHO better then blacklisting in some cases).

**Comment by ReikaKalseki** [comment]
Few of them ever should be generated, both from a sensibility (lakes of tritium?) and a balance standpoint.

**Comment by McJty** [comment]
Well you can already generate pretty weird stuff with RFTools dimensions so I wouldn't worry too much about the sensibility thing. But I do agree on the balance standpoint. If you feel it can't be balanced by making the liquid dimlets more expensive (both in rarity as well as power requirements) then I'm ok to blacklist them too. Will be for after my holiday however.

**Comment by McJty** [comment]
BTW. Another solution that *could* be considered is to make sure it is properly gated in your tech tree. And I actually do have a way to do that in my mod. I can make it so that certain features (like liquids) are:

a) Never randomly generated in dimensions.
b) Never returned as random dimlets in loot.

With that restriction the *only* way to get such a dimlet for some liquid is to actually already have that liquid (128 buckets of it). I have a mechanism in place to allow crafting material/liquid dimlets provided you already have the material to begin with. And if that's the only way to get those dimlets (features in dimensions) then they do have to follow proper RotaryCraft/ReactorCraft progression to get to that point.

**Comment by ReikaKalseki** [comment]
That brings up the same problem as ProjectE and bees did; producing some of a liquid is usually trivial. Producing usable quantities is not.

**Comment by McJty** [comment]
Ok. No problem. After my vacation I'll add the hook

**Comment by MyDeloreanWontStart** [comment]
But Reika.... jet fuel oceans! :-P


Also auto blacklist stuff like molten metals and refined liquids.

**Comment by ThisisCanada98** [comment]
Any possibility of there being a config option to revert back to being allowed to use the RotaryCraft fluids in RFtools dimensions?

**Comment by ReikaKalseki** [comment]
None of the RC fluids have blocks anyways. And no, configs to add exploits are silly.

**Comment by MyDeloreanWontStart** [comment]
Oh okay

**Comment by McJty** [comment]
Reika, I made a beta build of RFTools with this IMC added. Perhaps you might be able to test this if it works? You can download the beta from: http://minecraft.curseforge.com/mc-mods/224641-rftools/files/2248137

Instructions on how to use this IMC can be found here: https://github.com/McJty/RFTools/wiki/RFTools-Dimlet-IMC

**Comment by ReikaKalseki** [comment]
Does this work in the dev environment?

**Comment by McJty** [comment]
If you want a dev version for in dev environment you can download this instead: https://drone.io/github.com/McJty/RFTools/files/build/libs/rftools-3.12beta1.n438-dev.jar
As for an example. Somewhere in your preInit, something like this:

FMLInterModComms.sendMessage("rftools", "dimlet_blacklist", "Liquid.whatever");

**Comment by McJty** [comment]
Or better link for the dev version: the latest you can find here: https://drone.io/github.com/McJty/RFTools/files

**Comment by ReikaKalseki** [comment]
Done.

Thank you. :)
