### ISSUE TITLE
Crashing when right-cliocking Dimension Dialer

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [McJty/RFTools#331]
Every time I load my save-game or every time I use the portable teleport-thingy back home from another dimension and then use the dimension dialer, the game crashes with:

http://hastebin.com/xicojovoto.coffee

I have to break and place the dimension dialer every time in order to avoid crashes.

**Comment by McJty** [comment]
You mean the Dialing Device I suppose?

**Comment by McJty** [comment]
Hmm, are you really only allocating 1Gig memory to MC? I would strongly recommend increasing that to at least 3Gigs (but not more then 4Gigs)

**Comment by Unrepentant-Atheist** [comment]
Wot, no, I'm allocating 4GB. And yes, I mean the dialing device.

**Comment by smbarbour** [comment]
This isn't related to the issue, but you really should have the min and max memory sizes to be the same (otherwise, Java will constantly try to rearrange the contents of memory to shrink the amount of allocated memory).

As for the crash, the stacktrace seems to indicate that you are holding a block that is trying to be placed when you use dialing device.

**Comment by Unrepentant-Atheist** [comment]
It appears to be the terra pick axe from Botania that's causing this crash.

**Comment by McJty** [comment]
I recommend you also report this on the botania bug tracker then. The bug can be on either side

**Comment by McJty** [comment]
Closing because as for now there is no indication this is on RFTools side. Reopen if evidence comes up that it is RFTools fault.
