### ISSUE TITLE
Connecting to the server = timed out

### ISSUE THREAD

**Issue by DestinyPlayer** [McJty/RFTools#347]
Good evening. I have this weird problem that whenever I try to connect to my server I get timed out, and if I don't, I spawn in an absolutely empty world, and THEN get timed out after a few seconds. And the only thing I have to connect it to is RFTools exchanging its dim info.
http://pastebin.com/cibLtbGZ
If the full log is needed, I can upload it to somewhere.

**Comment by McJty** [comment]
I see nothing in this log indicating rftools at all. So I doubt this has something to do with rftools. If you find any further information that indicates that it is rftools then feel free to reopen this

**Comment by TerdyTheTerd** [comment]
I'm not sure how this is realted, but on my server when i update buildcraft and its add-ons to more current release my server timeouts anyone who tries to join, oddly enough when I remove rftools the timeouts stop. Not sure why it causes rftools to make them happen, but removing it fixes it so that has to mean something, either its directly causing it or doing some asm reflexive magic messing with buildcraft stuff, will upload logs when I get the chance
