### ISSUE TITLE
1.9.4 Timer causing lag

### ISSUE THREAD

**Issue by praus1** [McJty/RFTools#592]
Just set up an endergenic generator in RFTools 4.65 on Minecraft 1.9.4. It all seemed to be going pretty well till I set down the RFTools timer to try and regulate it. The moment I set down the timer I started having massive client side lag. FPS dropped from around 50-60 to 15-24 and I was seeing almost a slideshow. The moment I removed the timer, the lag cleared up again. I'm using Ender IO resdstone cables to send and receive signed from the timer. The idea being to restart the timer unless a pearl is lost.

**Comment by McJty** [comment]
This has also been observed on ForgeCraft and there it was found out that it was actually the EnderIO redstone conduits causing the lag. That team knows about it and maybe it is even fixed in latest versions. Not 100% sure. Maybe you could check that out? Putting the enderio redstone conduits in facades is working a bit too in older versions.

If it turns out it was the timer after all (which would surprise me really) then you can reopen this
