### ISSUE TITLE
[1.10.2] Crash when using a wrench on a Inventory Checker

### ISSUE THREAD

**Issue by Peach774** [McJty/RFTools#607]
Received this crash when rotating an inventory checker with a wrench: http://pastebin.com/0hmwNCRn

**Comment by Peach774** [comment]
This actually completely breaks the world since the tile entity is corrupt.

**Comment by McJty** [comment]
This is probably caused by whatever block the inventory checker is pointing too. What block was it? You should report to them.

To unbreak your world edit forge.cfg and enable the flag that removes tile entities with errors. The inventory checker will be gone.

Please let me know what block caused this. Thanks

**Comment by Peach774** [comment]
Blood altar from blood magic caused this

**Comment by McJty** [comment]
Ah, known bug but it should already be fixed. Are you using latest bloodmagic? Or maybe he hasn't released a new version with the bugfix in it yet
