### ISSUE TITLE
[suggestion] monitor RF transfer rate.

### ISSUE THREAD

**Issue by Tcll** [McJty/RFTools#676]
So I have a setup with `Ultimate Universal Cables` connecting `Ultimate Solar Panels` to a `P2P Tunnel - RF` and keep killing my ME because I'm using too much RF.

I've tried out the network monitor, but wasn't sure how to use the filter to clear out the junk resources, like the ME cables.

May I suggest a power meter like that in the mod `EnderIO` which I can place between the cable and tunnel which will monitor the RF transfer rate so I can know how much more I need to add.

I'm actually amazed EnderIO is the only mod that does something like this, but the problem with it is it must be connected to conduit to work, and conduit can't transfer RF like cryo-stabalized fluxduct or P2P tunnels, and I'm using multiples more RF than 20,000/t when 1 Ultimate Solar outputs 32,768/t, and I'm currently using 5 panels which isn't enough for my system.

EDIT: Oh and the OC Adapter is a joke, because you can only get the stored RF.

**Comment by McJty** [comment]
It is not possible in general to monitor RF transfer rate in general because the RF API does not have that information. You can only get how much RF is stored in something. Not how much went out or in.

The reason EnderIO can do this is exactly because it is limited to conduits which they handle themselves. So unfortunatelly not really possible I'm afraid
