### ISSUE TITLE
Dimlets disappearing

### ISSUE THREAD

**Issue by FiilTheThird** [McJty/RFTools#73]
I was playing on the Feed The Beast Infinity pack and came across a problem with the dimlet scrambler. When I shift clicked a stack of 2 or more dimlets into the scrambler only one dimlet would remain and the others just vanished. I tested it and it happened in single and multiplayer. I'm not sure if it's because of some other mods in the pack but I thought I should post it anyway.

**Comment by McJty** [comment]
I will investigate this. Thanks for reporting

**Comment by McJty** [comment]
Hmm. I cannot reproduce this. Note that if 3 dimlets go into the scrambler they will get scrambled to another dimlet (i.e. they go away and after a way a new one appears). Are you sure that was not what was happening?

**Comment by permdaddy** [comment]
This has happened to me too. 

If you have a stack of 2 or more of the same dimlet and shift click them into the scrambler, only 1 will go in 1 spot, but the other one in the stack is gone.

**Comment by McJty** [comment]
On what version of RFTools?

**Comment by Vanir2314** [comment]
I can confirm the bug.
If a stack of 2-16 is shift-clicked ot of your inventory into the Dimlet Scrambler only 1 Dimlet will appear in a slot. It is irrelevant wether or not there are already Dimlets in any of the slots. When having a stack on the cursor and clicking on the slots however, only one item will vanish, and the rest remains in the current stack.
I tested every RFTools version 2.40 onwards (up to 2.54), Testing environment is an otherwise unmodified FTB Infinity 1.20

**Comment by Mandabar** [comment]
The same thing happens for me shift clicking any stack of dimlets 2+ into an enscriber. Everything about 1 disappears and only the one makes it up to the enscriber window

**Comment by McJty** [comment]
Yes, seems that many people can reproduce this bug and I also could reproduce it on infinity. But I still have no clue why it fails. The big problem is that it works fine in my dev environment which makes it hard to debug.

**Comment by McJty** [comment]
FINALLY found out what the bug is. Next version (2.62) will hopefully fix this annoying bug.
