### ISSUE TITLE
[Suggestion] Better Storage Scanner extracting

### ISSUE THREAD

**Issue by Hallo89** [McJty/RFTools#760]
Here's a suggestion to refine the storage scanner a little bit:
You could remove the output slot and make the items one extract go directly into the inventory. Would be a heck of a lot easier to work with.
If you do that, you could make a bigger input space instead of just one slot to make fast inserting possible, for example with the mouse tweeks' click and drag whilst holding shift option

**Comment by McJty** [comment]
The problem is that in the future this will not work when autocrafting from RFTools Control is linked to this. Because then this will be asynchronous. i.e. you request an item and it might not be immeidatelly available as it has to be crafted. So you have to be able to close your inventory and then later open the tablet again to find the item there when it is ready. And so that can't be to a players inventory because the player may even have logged off before the craft is ready.

**Comment by Hallo89** [comment]
Maybe then create a new slot which takes the items autocrafted but extracting manually goes into the inventory? :D

**Comment by McJty** [comment]
Another thing that I could do is let it go to that slot but automatically move it over to the players inventory (if there is room) as soon as the gui opens (or is already open). Would that work?

**Comment by Hallo89** [comment]
That would be awesome!
I got on that because of your let's play, as you extracted several stacks of cobblestone but had to move them from the output slot to the inventory at every new stack

**Comment by McJty** [comment]
Implemented for next release
