### ISSUE TITLE
Space chamber alignment off by 1 Y

### ISSUE THREAD

**Issue by xenoflot** [McJty/RFTools#801]
Hi McJty,

I've been playing with using a space chamber to move a build. The move process works fine however...

I placed my builder at the same Y value as the space chamber control block. What I failed to notice was that the preview was showing me the whole thing was offset down by 1 Y value. In retrospect, I can see why, but to me at least, this isn't intuitive. Not sure how others feel but you might consider bumping the Y value by 1 when pasting.

Cheers

**Comment by McJty** [comment]
What? How is it offset down by 1 Y value? I don't get it

**Comment by xenoflot** [comment]
Sorry for the poor explanation!

If you consider the bottom-front-left corner of the area to be copied as xyz 0,0,0, the space chamber controller block sits at -1,-1,-1.

When you activate the Builder, it pastes 0,0,0 directly in front of it. Thus the builder is sitting at xyz 0,0,-1. So if you place the builder at the same Y level as the space chamber controller, the paste is 1 Y level lower than the original.

The preview **_did_** show me this so it's completely my fault! However I feel for natural operation, the builder should paste exactly relative to where the controller block is. That is, the builder should paste 0,0,0 up, right and in front by 1 (versus just 1 in front which is what I think it's doing now)

I hope that's clearer!
Thanks

**Comment by McJty** [comment]
Well a few things. First I consider the current way more intuitive. The area to be copied/moved is the area inside the space chamber container so that's what I expect to work with. The eight space chamber blocks are just markers. They don't represent the actual area.

Secondly I cannot change this now as this would not be compatible with existing builds that depend on current behaviour.

Thirdly there is a reason for this setup. It allows you to use a setup where you have another builder immediatelly outside the area affected by the space chamber. If the builder had to be at the same spot as the controller then this would not be possible easily.

**Comment by xenoflot** [comment]
I understand. Thanks very much for the comprehensive answer.
