### ISSUE TITLE
[1.10.2] Item dupe in 5.62alpha2 

### ISSUE THREAD

**Issue by katur239** [McJty/RFTools#868]
Using the new version (5.62alpah2) on 1.10.2 from curse with the new CompactLayer and the Coal Generator is duping Charcoal when shift clicking Charcoal into the gen.

**Comment by Tahkra** [comment]
Confirming this bug with the alpha versions of McJtyLib and RFTools. Specifically, I was able to duplicate items by having them present both in inventory and in a modular storage and shift clicking both into and out of the modular storage. The target inventory would receive the stack of items clicked, but they would not be removed from the origin inventory.

Downgrading both McJtyLib to 2.2.0 and RFTools 5.62 (non-alpha) versions fixes the issue. Downgrading RFTools without the library mod had no effect.

**Comment by McJty** [comment]
I'll check it out. It is exactly this kind of bug that I'm expecting with this

**Comment by McJty** [comment]
I cannot reproduce this at all. What version of compatlayer was being used? More details on how to reproduce this are useful too

**Comment by Tahkra** [comment]
I reproduced the bug again on a fresh creative world (MC 1.10.2, Forge 2151, custom modpack) with the following versions:

CompatLayer 1.10-0.0.17alpha
McJtyLib 1.11-2.2.0alpha2
RFTools 1.11-5.62alpha2

Steps to Reproduce

1. Place a Modular Storage block.
2. Place a Storage Card in Modular Storage block
3. Place half a stack of an item in the Modular Storage. I used emeralds most recently, but I was also able to duplicate sharpening kits from Tinkers' Construct.
4. Pull one emerald out and place in the player inventory.
5. Shift click the one emerald into the Modular Storage block.

Expected behavior: The half stack of emeralds increments back to 32 and the emerald in the player inventory is gone.

Actual behavior: The half stack of emeralds increments to 32 and the emerald in the player inventory remains.

NOTE: This bug only appears when the shift click does not create a new stack in the modular storage. For instance, if there is a stack of emeralds in the storage and a stack in the player inventory, the shift click will work as expected.

If you need, I can pastebin a modlist (~44 mods) if you can't reproduce the bug in your dev environment. I disabled MouseTweaks and Inventory Sorter during my testing so I don't think there's anything else conflicting, but you never know.

**Comment by McJty** [comment]
Ok, will try that once my rftools compiles again (doing big changes)

**Comment by katur239** [comment]
Also same versions as Tahkra.

Seems to be when there are partial stacks in each inventory. I was shift clicking 3 charcoal into the generator(it had 20) and it incremented the gen inventory by 3 until it hit 64, then consumed all but 1 from the stack in my inventory.

**Comment by McJty** [comment]
I can reproduce now

**Comment by McJty** [comment]
Bug fixed next release (was a problem in McJtyLib)
