### ISSUE TITLE
Storage Scanner shows wrong items for compacting drawers

### ISSUE THREAD

**Issue by pfmoore** [McJty/RFTools#943]
I've got a storage scanner interfacing to my storage drawers system. The only drawer I have listed in the scanner is the drawer controller, but that's connected to a set of normal drawers and compacting drawers.

Most things seem to show up fine, but I have 2 emeralds in a compacting drawer, and the scanner shows 2 emeralds and 1 emerald block present. If I try to extract the emeralds, that's fine, but if I try to extract the (non-existent) block of emerald, I get nothing (which is right, but I wouldn't have even expected the block to be showing).

**Comment by McJty** [comment]
This problem is hard to avoid. The storage controller acts like a virtual inventory over all other drawers. But rftools can't know that. It just sees it as an inventory. So it sees the emerald in the controller and then the emerald in the drawer and then it has no way to know that those are the same. The only solution is to not include the drawer in the scanner (i.e. remove it from the list) or else remove the drawers.

**Comment by pfmoore** [comment]
Sorry, I didn't explain very well. I do exclude the drawer - I just have the controller in the scanner. The problem seems to be that the scanner sees the controller reporting that it has emeralds and emerald blocks (because the compacting drawer can produce them) even though no emerald blocks are actually available (because we have less than 9 emeralds).

Regardless, it's a minor issue (it's just that the display in the scanner is misleading) so if it's just a result of how the storage drawers work, then that's fine.

**Comment by McJty** [comment]
Ah yes, well same problem really. The controller is a weird block. It acts as if the items are there when they are not
